// data/products.js
const products = [
  {
    id: 1,
    name: "MacBook Pro",
    price: 1299,
    imageUrl: "/categoryimages/smartwatches.png",
    isCompanyProduct: true,
    description: "The MacBook Pro delivers a powerful performance with the M1 chip and a stunning Retina display.",
    category: "Laptops",
    rating: 4.8,
    stock: 25,
    isFeatured: true,
    discount: '10%',

  },
  {
    id: 2,
    name: "Nike Air Max",
    price: 150,
    imageUrl: "/categoryimages/sneakers.png",
    isCompanyProduct: false,
    description: "Nike Air Max sneakers combine style and comfort with their iconic design and air cushioning.",
    category: "Footwear",
    rating: 4.5,
    stock: 50,
    isFeatured: false,
    discount: '5%',

  },
  {
    id: 3,
    name: "iPhone 13 Pro",
    price: 999,
    imageUrl: "/categoryimages/phones.png",
    isCompanyProduct: true,
    description: "The iPhone 13 Pro offers a Pro camera system, super retina display, and the powerful A15 Bionic chip.",
    category: "Smartphones",
    rating: 4.9,
    stock: 30,
    isFeatured: true,
    discount: '15%',

  },
  {
    id: 4,
    name: "Rolex Submariner",
    price: 7999,
    imageUrl: "/categoryimages/smartwatches.png",
    isCompanyProduct: false,
    description: "The Rolex Submariner is a timeless luxury dive watch known for its durability and precision.",
    category: "Watches",
    rating: 5.0,
    stock: 10,
    isFeatured: true,
    discount: '53%',

  },
  {
    id: 5,
    name: "Samsung Galaxy Tab",
    price: 499,
    imageUrl: "/categoryimages/tablets.png",
    isCompanyProduct: true,
    description: "The Samsung Galaxy Tab offers a versatile experience with its S Pen and stunning AMOLED display.",
    category: "Tablets",
    rating: 4.3,
    stock: 40,
    isFeatured: false,
    discount: '22%',

  },
  {
    id: 6,
    name: "Sony WH-1000XM4",
    price: 349,
    imageUrl: "/categoryimages/headphones.png",
    isCompanyProduct: false,
    description: "Industry-leading noise canceling with premium sound quality and up to 30 hours of battery life.",
    category: "Headphones",
    rating: 4.7,
    stock: 35,
    isFeatured: false,
    discount: '33%',

  },
  {
    id: 7,
    name: "Herschel Backpack",
    price: 89,
    imageUrl: "/categoryimages/bag.png",
    isCompanyProduct: true,
    description: "A modern take on the classic backpack, perfect for travel, work, or school with multiple compartments.",
    category: "Accessories",
    rating: 4.2,
    stock: 75,
    isFeatured: false,
    discount: '43%',

  },
  {
    id: 8,
    name: "LEGO Technic Car",
    price: 120,
    imageUrl: "/categoryimages/toys.png",
    isCompanyProduct: false,
    description: "Build and play with the LEGO Technic Car, featuring authentic design details and moving parts.",
    category: "Toys",
    rating: 4.9,
    stock: 20,
    isFeatured: true,
    discount: '12%',

  },
  {
    id: 9,
    name: "Dell XPS 13",
    price: 1099,
    imageUrl: "/categoryimages/protectors.png",
    isCompanyProduct: true,
    description: "The Dell XPS 13 is a sleek, powerful ultrabook with an InfinityEdge display and top-tier performance.",
    category: "Laptops",
    rating: 4.7,
    stock: 15,
    isFeatured: false,
    discount: '5%',

  },
  {
    id: 10,
    name: "Adidas Ultraboost",
    price: 180,
    imageUrl: "/categoryimages/sneakers.png",
    isCompanyProduct: false,
    description: "Adidas Ultraboost shoes offer unrivaled energy return with a sleek design for both running and style.",
    category: "Footwear",
    rating: 4.6,
    stock: 45,
    isFeatured: true,
    discount: '42%',

  },
  {
    id: 11,
    name: "Google Pixel 6",
    price: 799,
    imageUrl: "/categoryimages/phones.png",
    isCompanyProduct: true,
    description: "The Google Pixel 6 boasts a powerful camera, pure Android experience, and the custom Tensor chip.",
    category: "Smartphones",
    rating: 4.8,
    stock: 25,
    isFeatured: true,
    discount: '15%',

  },
  {
    id: 12,
    name: "Omega Speedmaster",
    price: 5999,
    imageUrl: "/categoryimages/powerbanks.png",
    isCompanyProduct: false,
    description: "The Omega Speedmaster is a luxury chronograph known as the first watch worn on the moon.",
    category: "Watches",
    rating: 5.0,
    stock: 8,
    isFeatured: true,
    discount: '35%',

  },
  {
    id: 13,
    name: "iPad Pro 11\"",
    price: 899,
    imageUrl: "/categoryimages/tablets.png",
    isCompanyProduct: true,
    description: "The iPad Pro 11\" combines ultra-fast performance with an incredible display and support for the Apple Pencil.",
    category: "Tablets",
    rating: 4.9,
    stock: 30,
    isFeatured: false,
    discount: '5%',

  },
  {
    id: 14,
    name: "Bose QuietComfort 45",
    price: 329,
    imageUrl: "/categoryimages/headphones.png",
    isCompanyProduct: false,
    description: "Bose QuietComfort 45 delivers industry-leading noise cancellation with long-lasting comfort and battery.",
    category: "Headphones",
    rating: 4.6,
    stock: 40,
    isFeatured: false,
    discount: '5%',

  },
  {
    id: 15,
    name: "North Face Duffel Bag",
    price: 99,
    imageUrl: "/categoryimages/bag.png",
    isCompanyProduct: true,
    description: "The North Face Duffel Bag is durable, weather-resistant, and perfect for both travel and adventure.",
    category: "Accessories",
    rating: 4.3,
    stock: 55,
    isFeatured: false,
    discount: '5%',

  },
  {
    id: 16,
    name: "Hot Wheels Monster Truck",
    price: 45,
    imageUrl: "/categoryimages/toys.png",
    isCompanyProduct: false,
    description: "The Hot Wheels Monster Truck is a fun, action-packed toy with rugged wheels and authentic styling.",
    category: "Toys",
    rating: 4.8,
    stock: 60,
    isFeatured: true,
    discount: '5%',

  },
  {
    id: 17,
    name: "Lenovo ThinkPad X1 Carbon",
    price: 1399,
    imageUrl: "/categoryimages/phones.png",
    isCompanyProduct: true,
    description: "The Lenovo ThinkPad X1 Carbon is a business-class laptop known for its performance and durability.",
    category: "Laptops",
    rating: 4.7,
    stock: 20,
    isFeatured: true,
    discount: '5%',

  },
  {
    id: 18,
    name: "Puma RS-X",
    price: 130,
    imageUrl: "/categoryimages/sneakers.png",
    isCompanyProduct: false,
    description: "The Puma RS-X sneakers feature bold colors and a chunky silhouette for a distinct streetwear style.",
    category: "Footwear",
    rating: 4.4,
    stock: 30,
    isFeatured: false,
    discount: '5%',

  },
  {
    id: 19,
    name: "OnePlus 9 Pro",
    price: 969,
    imageUrl: "/categoryimages/phones.png",
    isCompanyProduct: true,
    description: "The OnePlus 9 Pro offers premium flagship features with fast charging, a Fluid AMOLED display, and 5G support.",
    category: "Smartphones",
    rating: 4.7,
    stock: 35,
    isFeatured: false,
    discount: '5%',

  },
  {
    id: 20,
    name: "Tag Heuer Carrera",
    price: 4599,
    imageUrl: "/categoryimages/smartwatches.png",
    isCompanyProduct: false,
    description: "Tag Heuer Carrera is a luxury chronograph watch known for its racing-inspired design and precision.",
    category: "Watches",
    rating: 4.9,
    stock: 12,
    isFeatured: true,
    discount: '5%',

  },
];

export default products;
